[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

[dev]
  port = 8888
  publish = "static"
